version: '3.8'

services:
  db:
    build:
      context: .
      dockerfile: Dockerfile.authdb
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=auth
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  auth:
    build:
      context: .
      dockerfile: Dockerfile.auth
    ports:
      - "8000:8000"  # Предположим, auth сервис использует порт 8080
    depends_on:
      - db


volumes:
  pgdata:
